name: date_and_time
on:
  push:
  pull_request:

jobs:
  show-datetime:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print current date and time
        run: date
